# Generated by Django 4.1 on 2025-10-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALÁXIA', 'galáxia'), ('PLANETA', 'planeta'), ('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela')], default='', max_length=50),
        ),
    ]
