# Generated by Django 4.1 on 2025-10-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_fotografia_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALÁXIA', 'galáxia'), ('ESTRELA', 'estrela'), ('NEBULOSA', 'nebulosa'), ('PLANETA', 'planeta')], default='', max_length=50),
        ),
    ]
