# Generated by Django 4.1 on 2025-10-15 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_alter_fotografia_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('GALÁXIA', 'galáxia'), ('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('PLANETA', 'planeta')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 15, 13, 19, 4, 370605)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
