# Generated by Django 4.1 on 2025-10-17 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_fotografia_usuarios_alter_fotografia_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'nebulosa'), ('ESTRELA', 'estrela'), ('PLANETA', 'planeta'), ('GALÁXIA', 'galáxia')], default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 17, 15, 2, 0, 683978)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
